import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { QuoteProvider } from '@/context/QuoteContext';
import ToastProvider from '@/components/ToastContainer';

const poppins = Poppins({
  weight: ['600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Quotes by Kanye',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  favorite,
  newquotes,
}: Readonly<{
  children: React.ReactNode;
  favorite: React.ReactNode;
  newquotes: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ToastProvider>
          <QuoteProvider>
            <div className="flex flex-col justify-center items-center w-[65%] mx-auto py-12">
              <header>
                <h1 className="text-4xl text-center">Quotes by Kanye</h1>
              </header>
              <main className="w-full">
                {children}
                <div className="flex flex-row justify-between">
                  {favorite}
                  {newquotes}
                </div>
              </main>
            </div>
          </QuoteProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
